name: Gavy
favicon: null
layout_spectrum: 0.9923618028406054
typography_spectrum: 0.31273149186745286
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7715579839423299
  lightness: 0.5364817844238132
  saturation: 0.10413781506940722
  rhythmicContrast: 0.8435643000993878
purpose: []
